# Generated by Django 4.0.7 on 2022-11-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='User Name')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Create Date')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'User Name',
                'verbose_name_plural': 'User Name',
            },
        ),
    ]
