# Generated by Django 4.0.7 on 2022-11-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type Name')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commontype.commontype', verbose_name='Parent Type')),
            ],
            options={
                'verbose_name': 'Common Type',
                'verbose_name_plural': 'Common Type',
            },
        ),
    ]
