# Generated by Django 4.0.7 on 2022-11-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commontype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Storage Name')),
                ('size', models.FloatField(null=True, verbose_name='Storage Size')),
                ('commontype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commontype.commontype', verbose_name='Storage Type')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storage',
            },
        ),
    ]
