# Generated by Django 4.0.7 on 2022-09-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sample_txt', models.CharField(max_length=255)),
                ('sample_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Sample',
                'db_table': 'sample',
            },
        ),
    ]
