# Generated by Django 4.0.7 on 2022-11-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commontype', '0001_initial'),
        ('photoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Actor Name')),
                ('sex', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Actor Sex')),
                ('country', models.CharField(max_length=50, verbose_name='Actor Country')),
                ('description', models.TextField(verbose_name='Actor Description')),
                ('commontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commontype.commontype', verbose_name='Actor Type')),
                ('thumb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photoes.photo', verbose_name='Actor thumb')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actor',
            },
        ),
    ]
